- name: variables Demo
  hosts: localhost
  vars:
    URL: https://www.google.com
  vars_files:
    - vars.yml


  tasks:
    - name: Print URL
      debug:
        msg: URL - "{{ URL }}"

    - name: Print fruit name
      debug:
        msg: fruit - "{{ fruit }}"
      vars:
        fruit: apple

    - name: Print user Name
      debug:
        msg: user name - "{{ user_name }}"
