- name: variables Demo
  hosts: localhost
  vars:
    URL: https://www.google.com
  vars_files:
    - vars.yml


  tasks:
    - name: Print URL
      debug:
        msg: URL - "{{ URL }}"

    - name: Print fruit name
      debug:
        msg: fruit - "{{ fruit }}"
      vars:
        fruit: apple

    - name: Print user Name
      debug:
        msg: user name - "{{ user_name }}"

    - name: List modules
      debug:
        msg: Frist fruit name is {{ FRUITS.0 }}, second fruit name is {{ FRUITS.1 }}
      vars:
        FRUITS:
          - apple
          - banana
          - orange
    - name: map data
      debug:
        msg:  Course name is {{ Course.name }}, Course language is {{ Course.language }}
      vars:
        Course:
          name: Ansible
          language: Python

    - name: Execute some shell command
      ansible.builtin.shell:
        cmd: uptime
        register: OUT

    - name: Print output
      debug:
        msg: "{{ OUT }}"