- name: variables Demo
  hosts: localhost
  vars:
    URL: https://www.google.com

  tasks:
    - name: Print URL
      debug:
        msg: URL - "{{ URL }}"

    - name: Print Fruit name
      msg: Fruit name is "{{  fruit_name  }}"
      vars:
        fruit_name:
          - Apple
          - Orange
          - Mango
          - Pineapple
          - Watermelon