- name: variables Demo
  hosts: localhost
  vars:
    URL: https://www.google.com

  tasks:
    - name: Print URL
      debug:
        msg: URL - "{{ URL }}"

    - name: Print Fruit name
      debug:
        msg: "Fruit - {{ fruit }}"
        vars:
          fruit:
            - Apple
            - Orange 